### ISSUE TITLE
[Messenger] Migrate all Solr subscribers to Messenging for performance

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#400]

**Comment by ambroisemaupate** [comment]
In next Roadiz release you'll be able to handle Messages:

```yaml
messenger:
    failure_transport: failed_default
    transports:
        default:
            dsn: 'sync://'
            options: {  }
        async:
            dsn: 'doctrine://default?queue_name=async'
            options: {  }
        failed_default:
            dsn: 'doctrine://default?queue_name=failed_default'
            options: {  }
    routing:
        RZ\Roadiz\Message\GuzzleRequestMessage: async
        RZ\Roadiz\Core\SearchEngine\Message\SolrDeleteMessage: async
        RZ\Roadiz\Core\SearchEngine\Message\SolrReindexMessage: async
```
